### PR TITLE
docs: add source for budget.json and validation script

### PR DESCRIPTION
**Pull request by dsmedia**
Partially addresses #15

Changes made:
1. Adds source information for budgets.json to SOURCES.md
2. Creats a new script `validate_budget_data.py` in the scripts directory to validate the budget data against the original source

### CODE REVIEW

**Comment by domoritz** [comment]
Rather than validating, should the script just generate the file? We can always check that the diff is empty in git. It would be more similar to the other scripts. 

We could also run the script as part of the workflows if we want to have tests.

**Comment by domoritz** [comment]
What changed about the dataset? I'm asking since it affects what version bump this implies.

**Comment by dsmedia** [comment]
> What changed about the dataset? I'm asking since it affects what version bump this implies.

The original and script-generated budget.json files are identical in content, but differ in formatting: the original file has no space after the colons separating keys and values, while the script in my prior commit generated a json with a space after each colon. In this new commit, I've updated the script to generate a JSON formatted like the original.

## Timeline of changes:
1. **Original state**: `budget.json` had no spaces after colons separating keys and values.
2. **First commit**: 
   - Updated `budget.py` to generate JSON using default formatting of including spaces after colons.
   - Included the newly generated `budget.json` (identical content, different formatting).
3. **Latest commit**:
   - Updated `budget.py` to generate JSON without spaces after colons (matching original format).
   - Updated `budget.json` to match the original formatting.

**Comment by domoritz** [comment]
Thank you

**Pull request merged**
