### PR TITLE
Update movies.json to ensure dates use local timezone.

### PR DESCRIPTION
**Pull request by jheer**
Changes:
- Change release date format in `movies.json`. The previous `YYYY-MM-DD` format is parsed as a UTC date, leading to inaccurate plots for charts that assume dates in local time. Reformatted as `M/D/YYYY` and verified that major browsers (including Firefox) correctly `Date.parse` these strings as dates in local time.
- Update dev dependencies.

### CODE REVIEW

**Comment by domoritz** [comment]
I would like to reject this change as `M/D/YYYY` is not a standard date. vega-datasets is used not only in browsers but also from e.g. Python. Instead, I would suggest to force the parsing to assume local time. 

We might also want to consider changing the default interpretation in Vega-Lite to be UTC as dates are usually parsed as UTC but that's a separate discussion.

**Comment by jheer** [comment]
@domoritz Based on your comment I double checked the behavior of Pandas. With either format the column is read (using `pandas.read_json`) as a string. It appears one needs to provide a formatting string to `datetime.strptime` to map it to a datetime object. So I don't think we're really adding extra impedance here.

In general I would agree with your logic, but this dataset is a special case for multiple reasons. (1) Until very recently the date time formats in this file were an even bigger mess, so there is no strong historical or backwards compatibility argument here around the formatting. (2) I extensively use this dataset for pedagogical purposes. I don't want to have to update all the examples, but more importantly I don't want to have to introduce additional abstractions in the teaching materials. And of course I want the resulting plots to be accurate.

I agree that there is a larger discussion to be had around date parsing in Vega / Vega-Lite, but for the purposes of this PR I plan to go ahead and merge -- this is a bit time critical for me.

**Comment by jheer** [comment]
BTW, see also:
- https://github.com/vega/vega-datasets/blob/master/data/stocks.csv
- https://github.com/vega/vega-datasets/blob/master/data/sp500.csv

If you are more comfortable with the format already used by these existing files (e.g., `Jan 1 2000`) that is also an option.

**Comment by domoritz** [comment]
I'd be a bit more comfortable with `Jan 1 2000` as there is no ambiguity about whether the format is `M/D/YYYY` or `D/M/YYYY`. With your explanation, I'm okay to merge this.

**Comment by jheer** [comment]
Thanks! I'll first update the format to mirror our existing stock datasets.

**Pull request merged**
