### PR TITLE
Moved LICENSE, added it to package.json, minor mod

### PR DESCRIPTION
**Pull request by nyurik**

### CODE REVIEW

**Comment by domoritz** [comment]
Hmm, I'm not sure about the consequences here. The datasets are copies and modified from other datasets and so I'm not sure we can just mark them as bsd. I'll defer to someone else in @vega.

**Comment by nyurik** [comment]
@domoritz it's not possible to use a library if it + all of its dependencies don't clearly define their licenses. I think it's a legal requirement for larger projects.

The dataset is required by Vega lib (I'm not sure why btw), so Kibana's build system instantly flagged it as violating licensing.

**Comment by domoritz** [comment]
Good point. Vega-datasets is only used for tests so created a PR to make it a dev dependency (https://github.com/vega/vega/pull/1075).

I'm happy with whatever license the data becomes but I am not comfortable making an executing decision here. Maybe [ODbL](https://opendatacommons.org/licenses/odbl/) is a better fit than BSD.

**Comment by nyurik** [comment]
@domoritz technically each dataset should have its own license. If we want to be super accurate, each dataset should live in its own repo, with its own package.json, but that's going overboard. In any case, I don't think you can set ODbL or any other license on the whole repo and claim all datasets inside belong to it. On the other hand, you could set the root license and indicate its only for the code (scripts), while all the datasets each have their own license.

**Comment by domoritz** [comment]
The license is for the scripts and so I put it in the scripts folder. To find the license for the data files, you need to look at the original source then. I added a file for that at https://github.com/vega/vega-datasets/blob/gh-pages/sources.md. 

> On the other hand, you could set the root license and indicate its only for the code (scripts), while all the datasets each have their own license.

I don't see how that would work. Anyway, https://github.com/vega/vega/pull/1075 should fix the issue you originally had so I would prefer to close this.

**Pull request closed without merging**
