### PR TITLE
Added la-riots.json

### PR DESCRIPTION
**Pull request by palewire**
Hello. This is my first pull request. It is my effort to contribute a new dataset for the reasons outlined in #33.

This commit includes an exclusive dataset compiled and published several years ago by our team at the Los Angeles Times Data Desk. It is a GeoJSON file that lists everyone known to have died during the 1992 Los Angeles riots along with the location of their deaths.

I believe this file could help better illustrate a type of visualization common to data journalism: **Point maps**.

A common use case in a newsroom occurs when a graphic artist is asked to add pins to a map and zoom to their extent. Tooltips are added so users can explore individual records. Annotations often emphasize key points. Other layers like water, political boundaries and roads frequently enrich the map with geographic context.

I believe that this dataset could serve as an example of how such a map can be achieved with Vega. Using Altair I have drafted a rudimentary starting point. The Python code and Vega it generates is at the bottom of this message. I believe this example could be gradually enriched as Vega accumulates new features to teach users how to craft an effective tooltip, place an arrow with a text annotation and set a tighter extent by zooming in on a geoshape mark, which I've been told is not yet supported. 

visualization 1

Because the data set also includes numeric (age), temporal (date of death) and nominal (race) metadata on each victim, the set could be used in a wide range of other visualization examples as well. It contains only 63 records and should not add significantly to your package's weight.

```python
import altair as alt
import pandas as pd
from altair.expr import datum
from vega_datasets import data

properties = dict(
    projection={'type': 'mercator'},
    width=700,
    height=400
)

# Los Angeles County background
counties = alt.topo_feature(data.us_10m.url,'counties')
background = alt.Chart(counties).mark_geoshape(
    fill='lightgray',
    stroke='white'
).properties(**properties).transform_filter(datum.id == 6037)

# Riot points
riots_data = pd.read_csv("la-riots-deaths.csv")
points = alt.Chart(riots_data).mark_circle(size=15, color="red").encode(
    alt.Longitude('x:Q'),
    alt.Latitude('y:Q'),
).properties(**properties)

background + points
```
```json
{
  "layer": [
    {
      "mark": {
        "stroke": "white",
        "fill": "lightgray",
        "type": "geoshape"
      },
      "transform": [
        {
          "filter": "(datum.id === 6037)"
        }
      ],
      "data": {
        "format": {
          "feature": "counties",
          "type": "topojson"
        },
        "url": "https://vega.github.io/vega-datasets/data/us-10m.json"
      },
      "width": 700,
      "height": 400,
      "projection": {
        "type": "mercator"
      }
    },
    {
      "width": 700,
      "mark": {
        "color": "red",
        "type": "circle",
        "size": 15
      },
      "data": {
        "values": [
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "2009 W. 6th St.",
            "y": 34.0592814,
            "age": 18,
            "gender": "Male",
            "neighborhood": "Westlake",
            "first_name": "Cesar A.",
            "type": "Officer involved shooting",
            "last_name": "Aguilar",
            "x": -118.2739756
          },
          {
            "date": "1992-05-01",
            "race": "Latino",
            "address": "Main & College streets",
            "y": 34.062690100000005,
            "age": 42,
            "gender": "Male",
            "neighborhood": "Chinatown",
            "first_name": "George",
            "type": "Not riot-related",
            "last_name": "Alvarez",
            "x": -118.2340982
          },
          {
            "date": "1992-05-23",
            "race": "Latino",
            "address": "3100 Rosecrans Ave.",
            "y": 33.901662,
            "age": 40,
            "gender": "Male",
            "neighborhood": "Hawthorne",
            "first_name": "Wilson",
            "type": "Homicide",
            "last_name": "Alvarez",
            "x": -118.326816
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "Rosecrans & Chester avenues",
            "y": 33.903456899999995,
            "age": 30,
            "gender": "Male",
            "neighborhood": "Compton",
            "first_name": "Brian E.",
            "type": "Officer involved shooting",
            "last_name": "Andrew",
            "x": -118.2153903
          },
          {
            "date": "1992-05-03",
            "race": "Black",
            "address": "1600 W. 60th St.",
            "y": 33.985667,
            "age": 87,
            "gender": "Female",
            "neighborhood": "Harvard Park",
            "first_name": "Vivian",
            "type": "Death",
            "last_name": "Austin",
            "x": -118.30474099999999
          },
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "4404 S. Western Ave.",
            "y": 34.0034731,
            "age": 27,
            "gender": "Male",
            "neighborhood": "Vermont Square",
            "first_name": "Franklin",
            "type": "Officer involved shooting",
            "last_name": "Benavidez",
            "x": -118.30882150000001
          },
          {
            "date": "1992-05-02",
            "race": "Black",
            "address": "Harbor Freeway near Slauson Avenue",
            "y": 33.98916756,
            "age": 42,
            "gender": "Female",
            "neighborhood": "South Park",
            "first_name": "Carol",
            "type": "Death",
            "last_name": "Benson",
            "x": -118.2805037
          },
          {
            "date": "1992-04-30",
            "race": "White",
            "address": "2740 W. Olympic Blvd.",
            "y": 34.052068,
            "age": 30,
            "gender": "Male",
            "neighborhood": "Koreatown",
            "first_name": "Patrick",
            "type": "Homicide",
            "last_name": "Bettan",
            "x": -118.293181
          },
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "Vermont & Leeward avenues",
            "y": 34.058702200000006,
            "age": 49,
            "gender": "Male",
            "neighborhood": "Koreatown",
            "first_name": "Hector",
            "type": "Homicide",
            "last_name": "Castro",
            "x": -118.29165400000001
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "Santa Monica Boulevard & Seward Street",
            "y": 34.09129756,
            "age": 26,
            "gender": "Male",
            "neighborhood": "Hollywood",
            "first_name": "Jerel L.",
            "type": "Death",
            "last_name": "Channell",
            "x": -118.3323783
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "Vermont Avenue & 43rd Street",
            "y": 34.005485,
            "age": 15,
            "gender": "Male",
            "neighborhood": "Vermont Square",
            "first_name": "Gregory",
            "type": "Homicide",
            "last_name": "Davis Jr.",
            "x": -118.2915492
          },
          {
            "date": "1992-05-02",
            "race": "White",
            "address": "5800 block of South Vermont Avenue",
            "y": 33.98939885,
            "age": null,
            "gender": "Male",
            "neighborhood": "Vermont-Slauson",
            "first_name": "John",
            "type": "Homicide",
            "last_name": "Doe #80",
            "x": -118.29149540000002
          },
          {
            "date": "1992-05-01",
            "race": "White",
            "address": "3500 block of Winslow Drive",
            "y": 34.08778849,
            "age": 56,
            "gender": "Male",
            "neighborhood": "Silver Lake",
            "first_name": "Harry",
            "type": "Not riot-related",
            "last_name": "Doller",
            "x": -118.27876299999998
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "614 S. Locust Ave.",
            "y": 33.892421,
            "age": 35,
            "gender": "Male",
            "neighborhood": "Compton",
            "first_name": "Kevin J.",
            "type": "Not riot-related",
            "last_name": "Edwards",
            "x": -118.20025220000001
          },
          {
            "date": "1992-04-30",
            "race": "White",
            "address": "Slauson & 7th avenues",
            "y": 33.989048600000004,
            "age": 45,
            "gender": "Male",
            "neighborhood": "Hyde Park",
            "first_name": "Howard",
            "type": "Homicide",
            "last_name": "Epstein",
            "x": -118.3247424
          },
          {
            "date": "1992-05-02",
            "race": "Latino",
            "address": "7608 S. Compton Ave.",
            "y": 33.9198205,
            "age": 65,
            "gender": "Female",
            "neighborhood": "Compton",
            "first_name": "Juana",
            "type": "Homicide",
            "last_name": "Espinosa",
            "x": -118.24618810000001
          },
          {
            "date": "1992-05-01",
            "race": "White",
            "address": "Braddock Drive & Inglewood Boulevard",
            "y": 33.99267241,
            "age": 24,
            "gender": "Male",
            "neighborhood": "Del Rey",
            "first_name": "Kevin A.",
            "type": "Homicide",
            "last_name": "Evanahen",
            "x": -118.4144533
          },
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "1005 S. Fresno St.",
            "y": 34.0275527,
            "age": 15,
            "gender": "Male",
            "neighborhood": "Boyle Heights",
            "first_name": "Jose L.",
            "type": "Not riot-related",
            "last_name": "Garcia",
            "x": -118.2070419
          },
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "10700 block of Burin Avenue",
            "y": 33.93895407,
            "age": 15,
            "gender": "Male",
            "neighborhood": "Lennox",
            "first_name": "Mark",
            "type": "Officer involved shooting",
            "last_name": "Garcia",
            "x": -118.3537656
          },
          {
            "date": "1992-12-16",
            "race": "Latino",
            "address": "12834 Vanowen St.",
            "y": 34.1939342,
            "age": 32,
            "gender": "Male",
            "neighborhood": "Valley Glen",
            "first_name": "Elias",
            "type": "Homicide",
            "last_name": "Garcia Rivera",
            "x": -118.4137912
          },
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "2034 W. Pico Blvd.",
            "y": 34.0468443,
            "age": 36,
            "gender": "Male",
            "neighborhood": "Pico-Union",
            "first_name": "Andreas",
            "type": "Not riot-related",
            "last_name": "Garnica",
            "x": -118.2818793
          },
          {
            "date": "1992-05-01",
            "race": "Black",
            "address": "Holt & Loranne avenues",
            "y": 34.0628458,
            "age": 35,
            "gender": "Male",
            "neighborhood": "Pomona",
            "first_name": "Meeker",
            "type": "Homicide",
            "last_name": "Gibson",
            "x": -117.73064690000001
          },
          {
            "date": "1992-04-30",
            "race": "White",
            "address": "Lemon Avenue & Pacific Coast Highway",
            "y": 33.789857500000004,
            "age": 32,
            "gender": "Male",
            "neighborhood": "Long Beach",
            "first_name": "Matthew D.",
            "type": "Homicide",
            "last_name": "Haines",
            "x": -118.1785114
          },
          {
            "date": "1992-04-29",
            "race": "Black",
            "address": "Avalon Boulevard & Slauson Avenue",
            "y": 33.989245000000004,
            "age": 38,
            "gender": "Male",
            "neighborhood": "South Park",
            "first_name": "Jimmie",
            "type": "Death",
            "last_name": "Harris",
            "x": -118.26519950000001
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "Central Avenue & 112th Street",
            "y": 33.929472100000005,
            "age": 17,
            "gender": "Male",
            "neighborhood": "Green Meadows",
            "first_name": "DeAndre",
            "type": "Officer involved shooting",
            "last_name": "Harrison",
            "x": -118.2542949
          },
          {
            "date": "1992-05-01",
            "race": "Black",
            "address": "1439 E. Walnut",
            "y": 34.0217355,
            "age": 38,
            "gender": "Male",
            "neighborhood": "Central-Alameda",
            "first_name": "Paul D.",
            "type": "Homicide",
            "last_name": "Horace",
            "x": -118.2474139
          },
          {
            "date": "1992-05-01",
            "race": "Black",
            "address": "Main & 51st streets",
            "y": 33.9965216,
            "age": 56,
            "gender": "Female",
            "neighborhood": "South Park",
            "first_name": "Betty",
            "type": "Death",
            "last_name": "Jackson",
            "x": -118.27393049999999
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "11322 Alvaro St.",
            "y": 33.93229185,
            "age": 38,
            "gender": "Male",
            "neighborhood": "Watts",
            "first_name": "Dennis Ray",
            "type": "Officer involved shooting",
            "last_name": "Jackson",
            "x": -118.25375670000001
          },
          {
            "date": "1992-04-30",
            "race": "Asian",
            "address": "Willowbrook Avenue & Alondra Boulevard",
            "y": 33.888594299999994,
            "age": 25,
            "gender": "Male",
            "neighborhood": "Compton",
            "first_name": "Tranh",
            "type": "Homicide",
            "last_name": "Lam",
            "x": -118.2238673
          },
          {
            "date": "1992-04-30",
            "race": "Asian",
            "address": "Hobart Boulevard & 3rd Street",
            "y": 34.0689851,
            "age": 18,
            "gender": "Male",
            "neighborhood": "Koreatown",
            "first_name": "Edward Song",
            "type": "Homicide",
            "last_name": "Lee",
            "x": -118.3054392
          },
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "16th Street & Central Avenue",
            "y": 34.0264271,
            "age": 36,
            "gender": "Male",
            "neighborhood": "Downtown",
            "first_name": "Frank D.",
            "type": "Homicide",
            "last_name": "Lopez",
            "x": -118.2487649
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "Santa Monica Boulevard & Seward Street",
            "y": 34.09097156,
            "age": 18,
            "gender": "Male",
            "neighborhood": "Hollywood",
            "first_name": "Darnell R.",
            "type": "Death",
            "last_name": "Mallory",
            "x": -118.33413840000001
          },
          {
            "date": "1992-05-01",
            "race": "White",
            "address": "1800 block of East New York Drive",
            "y": 34.1785051,
            "age": 51,
            "gender": "Female",
            "neighborhood": "Altadena",
            "first_name": "Lucie R.",
            "type": "Homicide",
            "last_name": "Maronian",
            "x": -118.11343570000001
          },
          {
            "date": "1992-05-03",
            "race": "Black",
            "address": "near North Los Robles Avenue & Claremont Street",
            "y": 34.16686370000001,
            "age": 22,
            "gender": "Male",
            "neighborhood": "Pasadena",
            "first_name": "Howard Eugene",
            "type": "Officer involved shooting",
            "last_name": "Martin",
            "x": -118.14161299999999
          },
          {
            "date": "1992-04-30",
            "race": "White",
            "address": "Avalon Boulevard & 102nd Street",
            "y": 33.9437558,
            "age": 45,
            "gender": "Male",
            "neighborhood": "Green Meadows",
            "first_name": "Ira F.",
            "type": "Homicide",
            "last_name": "McCurry",
            "x": -118.26516299999999
          },
          {
            "date": "1992-05-01",
            "race": "Black",
            "address": "Florence Avenue & Cimarron Street",
            "y": 33.974591100000005,
            "age": 32,
            "gender": "Male",
            "neighborhood": "Chesterfield Square",
            "first_name": "Alfred V.",
            "type": "Homicide",
            "last_name": "Miller",
            "x": -118.3157372
          },
          {
            "date": "1992-04-29",
            "race": "Latino",
            "address": "120th Street & Central Avenue",
            "y": 33.923730400000004,
            "age": 23,
            "gender": "Male",
            "neighborhood": "Green Meadows",
            "first_name": "Arturo C.",
            "type": "Homicide",
            "last_name": "Miranda",
            "x": -118.2543429
          },
          {
            "date": "1992-05-01",
            "race": "Black",
            "address": "2137 E. 115th St.",
            "y": 33.930491700000005,
            "age": 24,
            "gender": "Female",
            "neighborhood": "Watts",
            "first_name": "Suzanne R.",
            "type": "Not riot-related",
            "last_name": "Morgan",
            "x": -118.2344108
          },
          {
            "date": "1992-08-12",
            "race": "White",
            "address": "1601 S. Western Ave.",
            "y": 34.0435539,
            "age": 20,
            "gender": "Male",
            "neighborhood": "Harvard Heights",
            "first_name": "Nissar",
            "type": "Homicide",
            "last_name": "Mustafa",
            "x": -118.3090341
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "Western Avenue & 92nd Street",
            "y": 33.952709000000006,
            "age": 27,
            "gender": "Male",
            "neighborhood": "Gramercy Park",
            "first_name": "Ernest",
            "type": "Homicide",
            "last_name": "Neal Jr.",
            "x": -118.30900600000001
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "San Pedro & 78th streets",
            "y": 33.9687806,
            "age": 21,
            "gender": "Male",
            "neighborhood": "Florence",
            "first_name": "Anthony",
            "type": "Homicide",
            "last_name": "Netherly",
            "x": -118.26951559999999
          },
          {
            "date": "1992-05-01",
            "race": "Black",
            "address": "Florence Avenue & Flower Street",
            "y": 33.9746575,
            "age": 21,
            "gender": "Male",
            "neighborhood": "Florence",
            "first_name": "Charles W.",
            "type": "Officer involved shooting",
            "last_name": "Orebo",
            "x": -118.28129009999998
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "Santa Monica Boulevard & Seward Street",
            "y": 34.090696,
            "age": 37,
            "gender": "Female",
            "neighborhood": "Hollywood",
            "first_name": "Juanita",
            "type": "Death",
            "last_name": "Pettaway",
            "x": -118.3331771
          },
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "4028 Santa Monica Blvd.",
            "y": 34.092221,
            "age": 20,
            "gender": "Male",
            "neighborhood": "Silver Lake",
            "first_name": "Juan A.",
            "type": "Homicide",
            "last_name": "Pineda",
            "x": -118.281326
          },
          {
            "date": "1992-05-03",
            "race": "Latino",
            "address": "12732 Bess St.",
            "y": 34.070238,
            "age": 23,
            "gender": "Male",
            "neighborhood": "Baldwin Park",
            "first_name": "Hugo G.",
            "type": "Not riot-related",
            "last_name": "Ramirez",
            "x": -117.997106
          },
          {
            "date": "1992-05-01",
            "race": "White",
            "address": "11690 Gateway Blvd.",
            "y": 34.0286551,
            "age": 68,
            "gender": "Male",
            "neighborhood": "Sawtelle",
            "first_name": "Aaron",
            "type": "Homicide",
            "last_name": "Ratinoff",
            "x": -118.4431
          },
          {
            "date": "1992-05-03",
            "race": "Latino",
            "address": "Pico Boulevard & Vermont Avenue",
            "y": 34.047256299999994,
            "age": 26,
            "gender": "Male",
            "neighborhood": "Pico-Union",
            "first_name": "Victor R.",
            "type": "Officer involved shooting",
            "last_name": "Rivas",
            "x": -118.291583
          },
          {
            "date": "1992-05-01",
            "race": "White",
            "address": "2882 W. 9th St.",
            "y": 34.055690000000006,
            "age": 33,
            "gender": "Male",
            "neighborhood": "Koreatown",
            "first_name": "William",
            "type": "Homicide",
            "last_name": "Ross",
            "x": -118.291274
          },
          {
            "date": "1992-05-20",
            "race": "Latino",
            "address": "3100 block of South Main Street",
            "y": 34.02062153,
            "age": 20,
            "gender": "Male",
            "neighborhood": "Historic South-Central",
            "first_name": "Juan V.",
            "type": "Homicide",
            "last_name": "Salgado",
            "x": -118.27137890000002
          },
          {
            "date": "1992-05-03",
            "race": "Black",
            "address": "San Diego Freeway & San Fernando Mission Boulevard",
            "y": 34.27185555,
            "age": 31,
            "gender": "Male",
            "neighborhood": "Mission Hills",
            "first_name": "Imad",
            "type": "Not riot-related",
            "last_name": "Sharaf",
            "x": -118.4717452
          },
          {
            "date": "1992-05-01",
            "race": "Latino",
            "address": "Vermont Avenue & Santa Monica Boulevard",
            "y": 34.0908675,
            "age": 25,
            "gender": "Male",
            "neighborhood": "East Hollywood",
            "first_name": "Jose",
            "type": "Homicide",
            "last_name": "Solorzano",
            "x": -118.29175500000001
          },
          {
            "date": "1992-04-30",
            "race": "Latino",
            "address": "2600 block of Florence Avenue",
            "y": 33.97418,
            "age": 20,
            "gender": "Male",
            "neighborhood": "Huntington Park",
            "first_name": "George A.",
            "type": "Homicide",
            "last_name": "Sosa",
            "x": -118.22518059
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "11322 Alvaro St.",
            "y": 33.9314634,
            "age": 31,
            "gender": "Male",
            "neighborhood": "Watts",
            "first_name": "Anthony J.",
            "type": "Officer involved shooting",
            "last_name": "Taylor",
            "x": -118.2531966
          },
          {
            "date": "1992-04-29",
            "race": "Black",
            "address": "4365 S. Vermont Ave.",
            "y": 34.004453000000005,
            "age": 42,
            "gender": "Male",
            "neighborhood": "Vermont Square",
            "first_name": "Dwight",
            "type": "Homicide",
            "last_name": "Taylor",
            "x": -118.292169
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "5213 Sunset Blvd.",
            "y": 34.0982485,
            "age": 26,
            "gender": "Male",
            "neighborhood": "East Hollywood",
            "first_name": "James L.",
            "type": "Homicide",
            "last_name": "Taylor",
            "x": -118.3037557
          },
          {
            "date": "1993-11-24",
            "race": "White",
            "address": "5510 W. Sunset Blvd.",
            "y": 34.0980819,
            "age": 54,
            "gender": "Male",
            "neighborhood": "Hollywood",
            "first_name": "Wallace",
            "type": "Homicide",
            "last_name": "Tope",
            "x": -118.30982240000002
          },
          {
            "date": "1992-04-29",
            "race": "White",
            "address": "San Fernando Road & San Fernando Mission Boulevard",
            "y": 34.28418731,
            "age": 15,
            "gender": "Male",
            "neighborhood": "San Fernando",
            "first_name": "Edward Anthony",
            "type": "Not riot-related",
            "last_name": "Travens",
            "x": -118.4430027
          },
          {
            "date": "1992-04-29",
            "race": "Latino",
            "address": "5100 block of West Slauson Avenue",
            "y": 33.9876036,
            "age": 33,
            "gender": "Male",
            "neighborhood": "Ladera Heights",
            "first_name": "Eduardo C.",
            "type": "Homicide",
            "last_name": "Vela",
            "x": -118.3687199
          },
          {
            "date": "1992-05-02",
            "race": "Black",
            "address": "11932 Cometa Ave.",
            "y": 34.287098,
            "age": 20,
            "gender": "Male",
            "neighborhood": "Pacoima",
            "first_name": "Fredrick",
            "type": "Homicide",
            "last_name": "Ward",
            "x": -118.412778
          },
          {
            "date": "1992-04-29",
            "race": "Black",
            "address": "4365 S. Vermont Ave.",
            "y": 34.00524354,
            "age": 18,
            "gender": "Male",
            "neighborhood": "Vermont Square",
            "first_name": "Louis A.",
            "type": "Homicide",
            "last_name": "Watson",
            "x": -118.29155659999999
          },
          {
            "date": "1992-04-30",
            "race": "Black",
            "address": "Western Avenue & 92nd Street",
            "y": 33.95276731,
            "age": 33,
            "gender": "Male",
            "neighborhood": "Gramercy Park",
            "first_name": "Elbert O.",
            "type": "Homicide",
            "last_name": "Wilkins",
            "x": -118.3100043
          },
          {
            "date": "1992-04-29",
            "race": "White",
            "address": "10621 Sepulveda Blvd.",
            "y": 34.263184,
            "age": 37,
            "gender": "Male",
            "neighborhood": "Mission Hills",
            "first_name": "John H.",
            "type": "Homicide",
            "last_name": "Willers",
            "x": -118.46777
          },
          {
            "date": "1992-04-29",
            "race": "Black",
            "address": "Gage & Western avenues",
            "y": 33.9823625,
            "age": 29,
            "gender": "Male",
            "neighborhood": "Chesterfield Square",
            "first_name": "Willie Bernard",
            "type": "Death",
            "last_name": "Williams",
            "x": -118.3089517
          }
        ]
      },
      "encoding": {
        "longitude": {
          "field": "x",
          "type": "quantitative"
        },
        "latitude": {
          "field": "y",
          "type": "quantitative"
        }
      },
      "height": 400,
      "projection": {
        "type": "mercator"
      }
    }
  ],
  "config": {
    "view": {
      "height": 300,
      "width": 400
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json"
}```

### CODE REVIEW

**Comment by domoritz** [comment]
This is a super interesting dataset. I wonder whether it makes sense to convert the data to CSV or a standard JSON file since the features are all points. It would make it a bit easier for people to work with. I would also like to rename `x` and `y` to `longitude` and `latitude`. 

Other than that, I think this dataset fits well into the collection. It has some interesting fields and it not too large. Thank you @palewire!

**Comment by palewire** [comment]
I'm happy to submit it as a CSV with those header changes. I will update this pull request shortly.

**Comment by palewire** [comment]
The changes you have requested have pushed with https://github.com/vega/vega-datasets/pull/34/commits/5cc72966109cf7f3198250ad8646860f954cefab

**Comment by domoritz** [comment]
Thank you! I will let @arvind merge so we have a second opinion.

**Comment by palewire** [comment]
@domoritz, I'm glad to hear it. I'm excited to cook up some Altair examples.

**Comment by palewire** [comment]
Back in this repo today pulling out some data for an Altair documentation example I'm working up and remembered this PR. Anything more I can do?

**Comment by domoritz** [comment]
Pinging @arvind. 

Otherwise, @kanitw can merge as well.

**Comment by arvind** [comment]
Thanks Ben!

**Comment by domoritz** [comment]
Thank you for the dataset @palewire.

**Comment by palewire** [comment]
Excellent. When the next version ships I'll be sure to work it into Altair's companion vega_datasets library for Python.

**Pull request merged**
