### PR TITLE
Added us-employment.csv

### PR DESCRIPTION
**Pull request by palewire**
I propose a new dataset be added: Changes in U.S. employment during ten years surrounding the Great Recession. 

I believe this dataset is needed to better illustrate bar charts with both positive and negative values. I drafted it in response to [a user request](https://twitter.com/ChekosWH/status/1051205399880159232) that such an example be provided. I did not find a dataset currently in the library that neatly fit this use case. 

One of the most common uses of this type of chart in my profession, journalism, is the monthly hiring numbers released by the Bureau of Labor Statistics.

Because job totals are an easy-to-grasp topic and the ten years in this dataset cover an important period in American history, I nominate its inclusion to serve as an example. 

Here's an Altair chart using this data that I plan to submit to that library's example gallery should this patch be accepted. 

```python
import altair as alt

source = alt.pd.read_csv("https://raw.githubusercontent.com/datadesk/vega-datasets/gh-pages/data/us-employment.csv")

alt.Chart(source).mark_bar().encode(
    x="month:T",
    y="change:Q",
    color=alt.condition(alt.datum.change > 0, alt.value("steelblue"), alt.value("orange")),
).properties(width=600)
```

visualization 1

Here's the corresponding source entry I propose:

> In the late 2000s the global economy was gripped by a crippling recession. One result: Massive job losses across the United States. The downturn in employment, and the slow recovery in hiring that followed, was tracked each month by the [Current Employment Statistics](https://www.bls.gov/ces/) program at the U.S. Bureau of Labor Statistics.

> This file contains the seasonally adjusted monthly total of non-farm employees from January 2007 through December 2016. The data series is known at the bureau as CES0000000001. It was downloaded on Oct. 13, 2018, and reformatted for use in this library. It is useful for illustrating bar charts, particularly those that report both negative and positive values.

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you! This looks really interesting. I wonder about two things.

First, should we omit the change as it can be computer with a window aggregate. I'm okay with leaving it in, though. 

Second, should we include more columns like the income and employment percentage, workforce size, and employment by sector? I'd like this dataset to be useful for more than one chart.

**Comment by palewire** [comment]
> First, should we omit the change as it can be computer with a window aggregate. I'm okay with leaving it in, though.

I calculated this column and added it to the data source with the goal of avoiding window functions. Since my objective is to create simple examples for newbies, I'd prefer to have the crucial column ready to serve. 

> Second, should we include more columns like the income and employment percentage, workforce size, and employment by sector? I'd like this dataset to be useful for more than one chart.

This is possible, but we'd have to identify and merge other datasets. The BLS "series" I downloaded is limited to employment totals. I selected the broadest category, all non-farm employees, because it is the typical stand-in for total work force in economics and journalism. The same totals are available for subsets known as "supersectors," such as manufacturing and construction. You can see some of them [here](https://data.bls.gov/cgi-bin/surveymost?ce). If you want measurements of things besides employment, we'd have to survey some of the other programs at BLS. 

That said, I'm reluctant to structure the data file in way where a pivot or other data transformation is necessary to create a chart. Whatever we do, I'd like to keep the file simple. 

Also, don't count the possibility that a simple dataset like this can be used in a number of different contexts. It's done in the news all the time. One additional example for Altair I'd like to hash out of this is a "Falkensee" chart. Here's a very draft I threw together in a couple minutes. It's rough but you get the idea.

```python

**Comment by domoritz** [comment]
Let's include the data from https://data.bls.gov/cgi-bin/surveymost?ce but not worry about other fields. Could you update the PR?

> That said, I'm reluctant to structure the data file in way where a pivot or other data transformation is necessary to create a chart. Whatever we do, I'd like to keep the file simple.

Completely agree.

**Comment by palewire** [comment]
Just to make sure I understand you right, you'd like to see additional columns added with the monthly totals for the different "supersectors" like manufacturing?

**Comment by domoritz** [comment]
I think that would make the dataset more universal but not increase the complexity. Yes, I think that would be nice.

**Comment by domoritz** [comment]
@palewire can you update the PR?

**Comment by domoritz** [comment]
@palewire can you update the PR?

**Comment by palewire** [comment]
Flying back home from a wedding trip on Sunday. I'll try to get to it then.

**Comment by palewire** [comment]
Alright. I've expanded the file to contain the monthly employment totals for all 22 "supersector" job categories tracked by the BLS. It is not a complete set covering all of the agency's top-level groups.

Here is my expanded sources entry, which explains the change.

> ## `us-employment.csv`

> In the late 2000s the global economy was gripped by a crippling recession. One result: Massive job losses across the United States. The downturn in employment, and the slow recovery in hiring that followed, was tracked each month by the [Current Employment Statistics](https://www.bls.gov/ces/) program at the U.S. Bureau of Labor Statistics.

> This file contains the monthly employment total in a variety of job categories from January 2006 through December 2015. The numbers are seasonally adjusted and reported in thousands. The data were downloaded on Nov. 11, 2018, and reformatted for use in this library.

> Totals are included for the [22 "supersectors"](https://download.bls.gov/pub/time.series/ce/ce.supersector) tracked by the BLS. The "nonfarm" total is the category typically used by economists and journalists as a stand-in for the country's employment total.

> A calculated "nonfarm_change" column has been appended with the month-to-month change in that supersector's employment. It is useful for illustrating how to make bar charts that report both negative and positive values

**Comment by domoritz** [comment]
Thank you so much! If you have the script to create this file, I'd love to have it added to the repo so that we can update the file in a few years.

**Comment by palewire** [comment]
If I was smarter, I would have a script. I pulled the series manually using the BLS data picker.

**Pull request merged**
