### PR TITLE
chore!: Rename `weather.json` -> `weekly-weather.json`

### LINKED ISSUE #633: breaking: Rename `weather.json` -> `weekly-weather.json`
Following #631, I was surprised to find that we have two *very different* datasets named `"weather"`.
I'd expected datasets sharing the same [*base name/stem*](https://en.wikipedia.org/wiki/Filename#Filename_extensions) to represent the same source. 
`"flights-200k"` is the only other duplicated name - but both the `.arrow` and `.json` files represent the same data.

I'm thinking ahead towards (https://github.com/vega/altair/pull/3631#issuecomment-2485922817), where there may be datasets with `.json` and `.parquet` versions.
In that world, a guarantee on a shared *stem* representing the same data would provide options to resolve incompatibilities in (https://github.com/vega/altair/pull/3631#issuecomment-2486370528)

I do understand renaming would have to be a **breaking change**, and should not be taken lightly.

# Usage
The following uses [jsdelivr-stats](https://www.jsdelivr.com/package/npm/vega-datasets?tab=stats) looking at the range of the *past year*.

Currently, [altair-viz/vega_datasets](https://github.com/altair-viz/vega_datasets) is by far the *greatest* source of traffic - which is pinned on [`v1.29.0`](https://github.com/vega/vega-datasets/releases/tag/v1.29.0).

## Versions

| Version   | Requests      |
| --------- | ------------- |
| `v1.29.0` | **6,802,781** |
| `v1.31.1` | 215,574       |
| `v2.7.0`  | 190,102       |

### `v1.29.0`

There is a [`weather.csv`](https://github.com/vega/vega-datasets/blob/v1.29.0/data/weather.csv) for this version - but is not accessible using the `python` api.
[`"weather"`](https://github.com/altair-viz/vega_datasets/blob/136e850447b49031f04baa137ce5c37a6678bbb1/vega_datasets/datasets.json#L258-L261) is defined as a reference to `weather.json` **only**.

The effect this has is quite apparent when comparing the traffic per-file:

| Dataset (`v1.29.0`) | Requests  |
| ------------------- | --------- |
| `movies.json`       | 1,804,118 |
| `population.json`   | 654,426   |
| ...                 | ...       |
| 40 most popular     | 5,000+    |
| `weather.json`      | 2,154     |
| `weather.csv`       | **31**    |

Given that `v1.29.0` is [baked into](https://github.com/altair-viz/vega_datasets/blob/136e850447b49031f04baa137ce5c37a6678bbb1/vega_datasets/core.py#L10-L12) the package - none of this usage would be impacted by the change.

[jsdelivr-npm](https://www.jsdelivr.com/documentation#id-npm) seems to be able to handle version-fallback in the event that anyone is using `@latest` - so maybe the impact of this change is fairly limited?

# Descriptions

<details><summary><code>weather.json</code></summary>
<p>

https://github.com/vega/vega-datasets/blob/719c388cc844392cda24517e4e0cda976b1d8519/SOURCES.md#L403-L405
https://github.com/vega/vega-datasets/blob/719c388cc844392cda24517e4e0cda976b1d8519/datapackage.json#L1207-L1215

</p>
</details> 

<details><summary><code>weather.csv</code></summary>
<p>

https://github.com/vega/vega-datasets/blob/719c388cc844392cda24517e4e0cda976b1d8519/SOURCES.md#L407-L409
https://github.com/vega/vega-datasets/blob/719c388cc844392cda24517e4e0cda976b1d8519/datapackage.json#L1679-L1718

</p>
</details> 

#### Side note
Having a unique [`name`](https://specs.frictionlessdata.io/data-resource/#name) per-[resource](https://specs.frictionlessdata.io/data-resource/) is part of the spec we haven't met yet.
I'm less interested in that part as we can just include the suffix if needed.

### PR DESCRIPTION
**Pull request by dangotbanned**
Closes #633

### Description
This PR renames a dataset and updates references to it in this repo.

I've added an alert to document this, which will render like below:

image

### Downstream work
The examples referenced in (https://github.com/vega/vega-datasets/issues/633#issuecomment-2552016729) will need to be updated after the major release.
- https://vega.github.io/vega/examples/weekly-temperature/
- https://vega.github.io/vega-lite/examples/bar_layered_weather.html

### CODE REVIEW

**Review by domoritz — APPROVED** [review]
Should we make a release before merging this or include it in the next major release?

**Comment by dangotbanned** [comment]
Thanks for approving @domoritz 

> Should we make a release before merging this or include it in the next major release?

No strong feelings from me. 
I thought the plan was that the next release was a major one? (https://github.com/vega/vega/issues/3990)

**Comment by domoritz** [comment]
Yep, I was just wondering whether there is anything we want to release before a major release.

**Comment by dangotbanned** [comment]
> Yep, I was just wondering whether there is anything we want to release before a major release.

Once this and #648 are merged, we'll have no more open issues.
Maybe worth opening another one for `v3` ideas (like #145)?

The only thing I've been considering was standardising date/time format strings.
So for any datasets that aren't *explicitly* being used to demonstrate [parsing](https://vega.github.io/vega-lite/docs/data.html#format) - could be transitioned to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

This isn't every case, but demonstrates some formats

### Integer year

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/barley.json#L1

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/disasters.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/driving.json#L3

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/jobs.json#L5

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/monarchs.json#L2

### Float time
`flights-200k.(arrow|json)`
```json
{"delay":-11,"distance":2419,"time":0.016666666666666666}
```

### String date/datetime

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/cars.json#L10

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/co2-concentration.csv?plain=1#L2

`flights-(2|5|10|20)k.json`
```json
"date":"2001/01/01 06:55",
```

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/github.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/iowa-electricity.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/la-riots.csv?plain=1#L2

`movies.json`
```json
"Release Date": "Jun 12 1998"
```

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/ohlc.json#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/political-contributions.json#L25

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/seattle-weather-hourly-normals.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/seattle-weather.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/sp500-2000.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/sp500.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/stocks.csv?plain=1#L2

`unemployment-across-industries.json`
```json
{"series":"Government","year":2000,"month":1,"count":430,"rate":2.1,"date":"2000-01-01T08:00:00.000Z"},
```

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/us-employment.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/weather.csv?plain=1#L2

https://github.com/vega/vega-datasets/blob/a88ff4c094e0eb4a88ad4f9793d33498bd39225d/data/wheat.json#L2

**Comment by domoritz** [comment]
Okay,I'll just make a release with all the changes then (when I get to it). Definitely make a datasets release before the others.

**Pull request merged**
