### PR TITLE
Finish transition to v2

### PR DESCRIPTION
**Pull request by domoritz**
Closes https://github.com/vega/vega-datasets/issues/145

See changelog in the changes.

I'm going to leave this open for discussion for a bit. Please let me know if you see any issues. I will make sure that we don't cause any problems with examples in the Vega and Vega-Lite example galleries.

### CODE REVIEW

**Comment by eitanlees** [comment]
Actually I am confused. The temperature data in `seattle-weather-hourly.csv` looks odd

visualization (4)

Is it celsius?

**Comment by domoritz** [comment]
I just downloaded the data from NOAA. The docs are at https://www1.ncdc.noaa.gov/pub/data/cdo/documentation/NORMAL_HLY_documentation.pdf. The docs say the data has average daily minimal temperatures for 30 years ending 2010. I used metric units, yes. 

Screen Shot 2020-06-02 at 10 31 38

**Comment by eitanlees** [comment]
I support the removal of the `iris` dataset. 

We will need to update:
- [Parallel Coordinate Plot Example](https://vega.github.io/vega-lite/examples/parallel_coordinate.html)
- [Faceted Density Plot](https://vega.github.io/vega-lite/examples/area_density_facet.html)
- [Density Docs](https://vega.github.io/vega-lite/docs/density.html#example-faceted-density-estimates)
- [Repeat Docs](https://vega.github.io/vega-lite/docs/repeat.html#scatterplot-matrix-splom)

once this is merged.

**Comment by domoritz** [comment]
I published `2.0.0-beta.2` so we can start updating the examples and see if we accidentally break anything.

I started Vega-Lite updates in https://github.com/vega/vega-lite/pull/6566. 

My plan is to release this weekend but I wanted to give folks time to voice their opinions on the breaking changes here.

**Comment by visnup** [comment]
Penguins?! _Goes to play with penguin data._

**Comment by domoritz** [comment]
🐧 Have a look at https://github.com/allisonhorst/palmerpenguins. Feel free to post links to any visualizations you are making that we could include in the Vega-Lite example gallery.

**Pull request merged**
