### PR TITLE
Add stacked area example

### PR DESCRIPTION
**Pull request by palewire**
During a discussion in [Altair issue #817](https://github.com/altair-viz/altair/pull/817), our group came to the conclusion that the existing dataset for illustrating stacked area charts, [unemployment across industries](https://vega.github.io/vega-lite/examples/stacked_area_normalize.html), is less than ideal.

Its large number of categories yield a noisy chart. And the mix of values don't change enough over time to make for an interesting normalized chart. See for yourself:

screenshot from 2018-05-06 22-02-58

To try to provide a stronger example to users, we developed a checklist for selecting a better dataset. We settled on:

- Require no data transformations 
- A time series 
- A small number of categories
- Values are percentages of a whole
- Tell an obvious, interesting visual "story."

After some back and forth, we settled on the attached dataset, which I propose for inclusion in this library to serve as its example for stacked area charts. 

The state of Iowa has dramatically increased its production of renewable wind power in recent years. This file contains the annual net generation of electricity in the state by source in thousand megawatthours. The dataset was compiled by the [U.S. Energy Information Administration](https://www.eia.gov/beta/electricity/data/browser/#/topic/0?agg=2,0,1&fuel=vvg&geo=00000g&sec=g&linechart=ELEC.GEN.OTH-IA-99.A~ELEC.GEN.COW-IA-99.A~ELEC.GEN.PEL-IA-99.A~ELEC.GEN.PC-IA-99.A~ELEC.GEN.NG-IA-99.A~~ELEC.GEN.NUC-IA-99.A~ELEC.GEN.HYC-IA-99.A~ELEC.GEN.AOR-IA-99.A~ELEC.GEN.HPS-IA-99.A~&columnchart=ELEC.GEN.ALL-IA-99.A&map=ELEC.GEN.ALL-IA-99.A&freq=A&start=2001&end=2017&ctype=linechart&ltype=pin&tab=overview&maptype=0&rse=0&pin=).

Here's what it looks like in Altair with very little configuration necessary.

```python
import pandas as pd
import altair as alt

data = pd.read_csv("https://gist.githubusercontent.com/palewire/6a8c512c518b98f85358242684584a81/raw/22ee97dba4a59a4cac8c02c70c68ecfbce50aba9/iowa.csv")
alt.Chart(data).mark_area().encode(
    x="year:O",
    y="net_generation:Q",
    color="source:N"
)
```

Here it is normalized.

```python
alt.Chart(data).mark_area().encode(
    x="year:O",
    y=alt.Y("net_generation:Q", stack="normalize"),
    color="source:N"
)
```

### CODE REVIEW

**Comment by palewire** [comment]
I suspect that newbies will be more comfortable with integer values.

In my experience, government and public domain datasets tend to represent annual data as simple numbers. And removing the need for a time parse lowers the configuration bar for beginners. That's been my experience as an Altair noob at least. I wonder what @jakevdp thinks.

**Comment by domoritz** [comment]
I updated my comment above with the spec that uses `temporal` with time in ISO format. I like that it doesn't add the white space at the beginning and the end. Luckily, you wouldn't have to worry about parsing dates (as long as you set `type: temporal`) but I can see that this adds one more thing to understand. 

I also noticed that you merged coal and natural gas. I think seeing these separately may be interesting. Too bad that "other renewables" is a single category so we don't know whether it's wind, water, or solar. Oh well, maybe these details distract from the main story the graph tells.

**Comment by jakevdp** [comment]
Do you know what, if any, license this data is released under? That would be worth noting in the ``sources.md`` listing.

**Comment by palewire** [comment]
This is government published by the United States government, so it is public domain and free for all reuse.

**Comment by jakevdp** [comment]
That's great! Once this is merged here, we should import it as a local datasets in https://github.com/altair-viz/vega_datasets

**Comment by domoritz** [comment]
Thank you for the explanation @palewire! Let's keep the dataset simple then but I'm still on the fence about using ISO dates. 

@kanitw what do you think?

**Comment by kanitw** [comment]
I think integer date is fine.  We should provide an example to guide people how to parse year integer anyway

**Comment by domoritz** [comment]
Okay. I suggest that you use parsing in the Altair example @palewire then, okay? The ordinal axis looks a bit odd and also you would miss potentially missing years.

**Comment by kanitw** [comment]
Yes, definitely use temporal scale.

**Comment by domoritz** [comment]
I think we agreed that it's okay not to change the CSV but instead add the `format.parse` block to the Vega-Lite/Altair specifications.

**Comment by palewire** [comment]
Just to cover all bases, I added a second "date" column with the ISO format in addition to the "year" integer field. 

On the Altair end, we'll have to decide if we want to include the more complex `timeUnit` option in examples for beginners. Without it, the chart looks like this:

```python
import pandas as pd
import altair as alt

data = pd.read_csv("https://raw.githubusercontent.com/datadesk/vega-datasets/stacked-area-example/data/iowa-electricity.csv")

alt.Chart(data).mark_area().encode(
    x=alt.X("date:T", timeUnit="year"),
    y="net_generation:Q",
    color="source:N"
)
```

visualization 18

With the extra config, the x-axis labels look better.

```python
alt.Chart(data).mark_area().encode(
    x=alt.X("date:T", timeUnit="year"),
    y="net_generation:Q",
    color="source:N"
)
```

visualization 19

**Comment by domoritz** [comment]
We've fixed this behavior in Vega-Lite. See https://github.com/vega/vega-lite/pull/3711

**Comment by domoritz** [comment]
I'm not a huge fan of having both date and year. We should either decide to have a short file format (using only year) or a short spec withough speciifc parsing (using ISO dates).

**Comment by palewire** [comment]
Currently Altair doesn't know how to parse the year on its own. Here's what I get.

```python
alt.Chart(data).mark_area().encode(
    x="year:T",
    y="net_generation:Q",
    color="source:N"
)
```
visualization 20

**Comment by domoritz** [comment]
What about ISO dates?

```
alt.Chart(data).mark_area().encode(
    x="date:T",
    y="net_generation:Q",
    color="source:N"
)
```

**Comment by palewire** [comment]
That works fine. You can see that in the example above my previous one.

**Comment by domoritz** [comment]
I'd be inclined to just have date (with ISO date format) then. Does anyone have strong feelings against it?

**Comment by jakevdp** [comment]
> Currently Altair doesn't know how to parse the year on its own. Here's what I get.

That behavior is Vega-Lite, not Altair... integer data assigned a temporal type is assumed to represent unix time stamps (i.e. seconds since Jan 1, 1970).

If you convert the integer column to a string before passing the data to Altair, then they will be interpreted as years.

**Comment by palewire** [comment]
If that is Vega-Lite's policy on integers, and y'all are firm that stacked area examples should be encoded as temporal data, then I think I agree with @domoritz that the column shipped with this dataset should be the ISO date. 

However, I do think that we've stumbled on a pain point for these libraries. Annual data that users acquire will routinely be recoded as integers. That's just the way of the world. I suspect it's probably best to deal with this issue separately, but IMHO there should be a canonical way to deal with year integers that "just works." My approach with Altair has been to encode the values as ordinal. I'm not attached to it, but even that is a little obscure for newbies. I could imagine asking users to convert the integers to datetimes being more straightforward, though it will require more work on their part. If that's the route, I'd like to see some Altair helper or helped with the conversions.

**Comment by palewire** [comment]
I've edited the file to remove the integer. And renamed the ISO column as `year`. Pushed.

**Comment by jakevdp** [comment]
Note that there are two different scenarios:

- integers, when interpreted as dates by vega, are treated as unix time stamps
- strings containing four integers, when interpreted as dates by vega, are treated as years

**Comment by jakevdp** [comment]
If you don't want to use ISO dates, but you want the dates to "just work", you could put them in quotations in the file so they will be interpreted as strings rather than integers from the beginning.

**Comment by domoritz** [comment]
Unfortunately, browsers handle date parsing differently so you have to be careful with automatically parsing anything besides ISO 8601 dates (`2010-03-01`) and RFC2822 dates (`Mon, 25 Dec 1995 13:30:00 GMT`). 

The safest way is to use `data.format.parse={year: 'date:%y'}`. I'm open to suggestions to improve the behavior in Vega-Lite but I think we are close to the optimal here. Keep in mind that Vega-Lite never sees the data.

**Comment by domoritz** [comment]
Thanks everyone for the discussion!

**Pull request merged**
