### PR TITLE
feat: Use a datetime column in `flights-3m.parquet`

### LINKED ISSUE #641: Use a datetime column in `flights-3m.parquet`
_Originally posted by @dangotbanned in [#627](https://github.com/vega/vega-datasets/issues/627#issuecomment-2481321593)_

In the screenshot from https://github.com/vega/vega-datasets/issues/627#issuecomment-2480823441, you can observe a datetime represented in `"MMDDHHMM"` format.

After reading through #626, I see that this is one of 3 options:

<details><summary>Format options</summary>
<p>

### New Generation Script

_New file: `flights.py`_

A comprehensive tool for processing U.S. DOT (BTS) On-Time Flight Performance data with enhanced flexibility and features. Creates date formats used in this repo.
#### Output Format Options
| Format       | Example            | Description           |
| ------------ | ------------------ | --------------------- |
| **MMDDHHMM** | **`06142330`**     | **June 14, 23:30**    |
| ISO          | `2023/06/14 23:30` | ISO-style datetime    |
| Decimal      | `23.75`            | 23:45 in decimal form |

</p>
</details> 

I've done some work looking into the cost of storing the column as a datetime (not a formatted string)

<details><summary>Conversion</summary>
<p>

```py

import polars as pl
from altair.datasets import Loader

load = Loader.from_backend("polars")
flights: pl.LazyFrame = load("flights-3m", tag="v2.11.0").lazy()

# NOTE: Assuming year is `2001`
date_conv: pl.Expr = (
    pl.concat_str(pl.lit("01"), "date").str.to_datetime("%y%m%d%H%M").alias("date")
)
delay_conv: pl.Expr = pl.duration(minutes=pl.col("delay")).alias("delay")

flights_date: pl.DataFrame = flights.with_columns(date_conv).collect()
flights_date_delay: pl.DataFrame = flights.with_columns(date_conv, delay_conv).collect()

```

</p>
</details> 

<details><summary>Size comparison</summary>
<p>

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QUOQFtMKEPMUBaNgFYDAIxgsALACY2LABwB2O3ICMYYwE4HxzG7mYDMLZgYCAyIGpyAE4A1sqEAJ4ADprIIIkQJOLclHAAXikAbFwghBAQADbEiSiEkaSYYZhQkHQkSKg85RCRyvCY5XRaCcl0AASQ5aRqUJQg3OWYCE2DHeVy3uUAYrwAynkpzubc3VhEWsYQhKVqodzDKSoQaiRy5bcgAB7Kch9ws6vrfrbIh7fIoQ5hPoDLQ5fKjAAUamMAEo5iBKGBXilQHQnnISCgANrOZycZwGAC6YXuWgAjqQ5EQ4IpiGhNGF4t9fv9QGsNsDCKCDkcSsyFgBBcqIKBaBYwLKiwgSqAIBYoYrEJWYAAaKF05gMdzFmAAmnqSdwEJF6DU6pgjVqtLlKIQxpA1IlIphKDloKMFmy3pCsNDUu7Pd7fVAAPoB-poyjdcSpOjesDLNpommpbqtVRBsKMEQIMTKF2YarIdhhRJRdT-QmgVQaLS1yLqaMsdwJ-o+ZOgbMgTKYSJoV5opotNoNz4gKncYwkFbozELWaSCkOtUdQiYD7JkAwKUlwiUXQsNQAOjb9MwCte0tlmHlaMZYEY3RhikiCpgu324LmGEAAkGJFhEWhiIQiSUMgAD0cFsggciXggzKMKQxiXnAEBwWBmARIhixyLoUq7ohBiXtYl7OJeABWiYyrIChyJQd48toLH6EYpgWNYdiOLYLhuJ49jeL4-iBMERIDkkmBuhUUwzFoOiYAA1Kmayctw4Zej6OExnGbzIKS6L7AiSKoiZ5iXuY7gGAUBjmM4bAFIcbDOCw9gyLJIzjIp0z-Jxu4af0cjaTwHp6VGsaYIG4LFLCmAWSi4IsJeBTmCwlgFPZdgOO4XYGD5JRyQpkyBSpCjqZp4VorpkYGbF8UmfY2TmYiqUmel5JeQYnmOJY7guc4BQlfc5VKUFqmhVp9VPBG+nQM18bIJYljtXCnVWZ5NH2EY5j7e47j2O4ljmLY41lf5FXKSm1XzVFjXLUZ4Kbcl21pZeAksEYthsOYgMsCwY2cL58k3VNVW7o9i0xa9JmJR1lngpYl4nfYtjOLYF3uGw9iHfjV1+RMUP3TDOkLdFTUI84bVmVtKMmWjw0AwY9huS5thdjjxMQ6TlXk5olNPUthlxat63vSlO1o7YBTWC59kGFjhiHXzk2CyAxiscLkVwzTEvGaZSUy6jGUGB59g2DlljZcNGuQ1rOtsbD1MvUbCXS59zOXuznkY1jXnWN5YOlSTAV3drutu894stXT3tM84aOW5jZ1FPLVjs5dYcTU7Ucu3rDViytxlSwzH3J2jBqOGwDi5etRQExu0hAA)

Image

</p>
</details> 

<details><summary><code>python</code> library support</summary>
<p>

`polars`

```
shape: (3_000_000, 5)
┌─────────────────────┬──────────────┬──────────┬────────┬─────────────┐
│ date                ┆ delay        ┆ distance ┆ origin ┆ destination │
│ ---                 ┆ ---          ┆ ---      ┆ ---    ┆ ---         │
│ datetime[μs]        ┆ duration[μs] ┆ i64      ┆ str    ┆ str         │
╞═════════════════════╪══════════════╪══════════╪════════╪═════════════╡
│ 2001-01-01 00:01:00 ┆ -13m         ┆ 2345     ┆ ANC    ┆ LAX         │
│ 2001-01-01 00:03:00 ┆ -20m         ┆ 1946     ┆ LAX    ┆ ATL         │
│ 2001-01-01 00:10:00 ┆ 0µs          ┆ 1671     ┆ PHX    ┆ DTW         │
│ 2001-01-01 00:20:00 ┆ 10m          ┆ 1709     ┆ SEA    ┆ STL         │
│ 2001-01-01 00:22:00 ┆ -13m         ┆ 1736     ┆ SFO    ┆ STL         │
│ …                   ┆ …            ┆ …        ┆ …      ┆ …           │
│ 2001-06-30 23:58:00 ┆ 30m          ┆ 215      ┆ ATL    ┆ SAV         │
│ 2001-06-30 23:59:00 ┆ 1h 27m       ┆ 496      ┆ PIT    ┆ BOS         │
│ 2001-06-30 23:59:00 ┆ 9m           ┆ 151      ┆ ATL    ┆ HSV         │
│ 2001-06-30 23:59:00 ┆ 1h 23m       ┆ 641      ┆ DFW    ┆ DEN         │
│ 2001-06-30 23:59:00 ┆ 16m          ┆ 594      ┆ ATL    ┆ DTW         │
└─────────────────────┴──────────────┴──────────┴────────┴─────────────┘
```

`pandas`

```
                       date             delay  distance origin destination
0       2001-01-01 00:01:00 -1 days +23:47:00      2345    ANC         LAX
1       2001-01-01 00:03:00 -1 days +23:40:00      1946    LAX         ATL
2       2001-01-01 00:10:00   0 days 00:00:00      1671    PHX         DTW
3       2001-01-01 00:20:00   0 days 00:10:00      1709    SEA         STL
4       2001-01-01 00:22:00 -1 days +23:47:00      1736    SFO         STL
...                     ...               ...       ...    ...         ...
2999995 2001-06-30 23:58:00   0 days 00:30:00       215    ATL         SAV
2999996 2001-06-30 23:59:00   0 days 01:27:00       496    PIT         BOS
2999997 2001-06-30 23:59:00   0 days 00:09:00       151    ATL         HSV
2999998 2001-06-30 23:59:00   0 days 01:23:00       641    DFW         DEN
2999999 2001-06-30 23:59:00   0 days 00:16:00       594    ATL         DTW

[3000000 rows x 5 columns]
```

`pyarrow`

```
pyarrow.Table
date: timestamp[us]
delay: duration[us]
distance: int64
origin: large_string
destination: large_string
----
date: [[2001-01-01 00:01:00.000000,2001-01-01 00:03:00.000000,2001-01-01 00:10:00.000000,2001-01-01 00:20:00.000000,2001-01-01 00:22:00.000000,...,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000],[2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,...,2001-01-16 22:49:00.000000,2001-01-16 22:49:00.000000,2001-01-16 22:49:00.000000,2001-01-16 22:49:00.000000,2001-01-16 22:49:00.000000],...,[2001-06-22 15:10:00.000000,2001-06-22 15:10:00.000000,2001-06-22 15:10:00.000000,2001-06-22 15:10:00.000000,2001-06-22 15:10:00.000000,...,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000],[2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,...,2001-06-30 23:58:00.000000,2001-06-30 23:59:00.000000,2001-06-30 23:59:00.000000,2001-06-30 23:59:00.000000,2001-06-30 23:59:00.000000]]
delay: [[-780000000,-1200000000,0,600000000,-780000000,...,-240000000,480000000,1380000000,720000000,-420000000],[-180000000,1320000000,720000000,600000000,480000000,...,-240000000,-1020000000,-2700000000,-540000000,-1080000000],...,[2220000000,960000000,360000000,240000000,-240000000,...,240000000,-360000000,360000000,360000000,360000000],[-600000000,-300000000,-660000000,-660000000,-360000000,...,1800000000,5220000000,540000000,4980000000,960000000]]
distance: [[2345,1946,1671,1709,1736,...,469,621,581,1679,324],[177,383,813,432,594,...,116,1865,1750,1750,1900],...,[1557,354,317,248,104,...,594,1024,1121,2329,867],[834,813,810,1972,200,...,215,496,151,641,594]]
origin: [["ANC","LAX","PHX","SEA","SFO",...,"IAH","ORD","ATL","SMF","GPT"],["TYS","BTR","PHL","DFW","ORD",...,"CVG","SAN","DTW","LAS","LAX"],...,["PHL","DFW","MKE","SAT","SHV",...,"ATL","EWR","BOS","LAX","ORD"],["MCO","STL","CVG","MIA","BNA",...,"ATL","PIT","ATL","DFW","ATL"]]
destination: [["LAX","ATL","DTW","STL","STL",...,"MEM","BWI","FLL","STL","MEM"],["CLT","DFW","STL","MEM","MDT",...,"CMH","CVG","LAS","DTW","CVG"],...,["DEN","CRP","STL","DAL","MLU",...,"DTW","PBI","MCO","BWI","BOS"],["PIT","PHL","PWM","PHX","MEM",...,"SAV","BOS","HSV","DEN","DTW"]]
```

</p>
</details>

Admittedly, we'd still need add (if possible) support for duration/timedelta on the `altair`-side:
- [altair/utils/core.py#L418-L425](https://github.com/vega/altair/blob/a0c091eca897e1b9eaa6bb70d8ae8dc1deff9e60/altair/utils/core.py#L418-L425)
- [altair/utils/core.py#L484-L491](https://github.com/vega/altair/blob/a0c091eca897e1b9eaa6bb70d8ae8dc1deff9e60/altair/utils/core.py#L484-L491)

However, the `date` column is supported, fairly cheap and **consistently parsed**.

That last point is something we've encountered as an issue with other datasets (see https://github.com/vega/altair/pull/3631#issuecomment-2480816377)

### PR DESCRIPTION
**Pull request by dangotbanned**
Closes #641 

## Related
- https://github.com/vega/altair/pull/3631#issuecomment-2480816377

## Description

If I've understood the *existing* script correctly; then this should produce a datetime/timestamp column for `"date"`.
Or more correctly, it won't convert to a format string for `.parquet` - as it supports data types.

## Question

@dsmedia I haven't run the script, as I'm unsure on:

- What environment is needed for the script?
- How exactly is the [linked data](https://www.transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FGJ&QO_fu146_anzr=b0-gvzr) selected?
	- The doc says 1 per month
	- `flights-3m.parquet` has 6 months
	- `flights-?k.json` have 3 months?
- What were the most recent CLI args used?

### Update
In (https://github.com/vega/vega-datasets/pull/642/commits/a908adb8477c9b7cdebc42a77eda3c381b2c8292) I opted for making the change in place.

<details><summary>Fix script</summary>
<p>

```py
from pathlib import Path
import polars as pl

def fix_inplace_3m_parquet(
    fp: Path, /, year: int | str, *, column: str = "date"
) -> None:
    year_zero_pad = str(year)[-2:]
    if len(year_zero_pad) != 2:
        raise TypeError(year)

    ldf = pl.scan_parquet(fp)
    if not ldf.collect_schema()[column].is_temporal():
        date_conv: pl.Expr = (
            pl.concat_str(pl.lit(year_zero_pad), column)
            .str.to_datetime("%y%m%d%H%M")
            .alias(column)
        )
        ldf.with_columns(date_conv).collect().write_parquet(fp, compression_level=22)

>>> fix_inplace_3m_parquet(
...     Path.cwd() / "data" / "flights-3m.parquet", year=2001, column="date"
... )
```

</p>
</details> 

## Example
```py
from pathlib import Path
import polars as pl

>>> pl.read_parquet(Path.cwd() / "data" / "flights-3m.parquet")
shape: (3_000_000, 5)
┌─────────────────────┬───────┬──────────┬────────┬─────────────┐
│ date                ┆ delay ┆ distance ┆ origin ┆ destination │
│ ---                 ┆ ---   ┆ ---      ┆ ---    ┆ ---         │
│ datetime[μs]        ┆ i64   ┆ i64      ┆ str    ┆ str         │
╞═════════════════════╪═══════╪══════════╪════════╪═════════════╡
│ 2001-01-01 00:01:00 ┆ -13   ┆ 2345     ┆ ANC    ┆ LAX         │
│ 2001-01-01 00:03:00 ┆ -20   ┆ 1946     ┆ LAX    ┆ ATL         │
│ 2001-01-01 00:10:00 ┆ 0     ┆ 1671     ┆ PHX    ┆ DTW         │
│ 2001-01-01 00:20:00 ┆ 10    ┆ 1709     ┆ SEA    ┆ STL         │
│ 2001-01-01 00:22:00 ┆ -13   ┆ 1736     ┆ SFO    ┆ STL         │
│ …                   ┆ …     ┆ …        ┆ …      ┆ …           │
│ 2001-06-30 23:58:00 ┆ 30    ┆ 215      ┆ ATL    ┆ SAV         │
│ 2001-06-30 23:59:00 ┆ 87    ┆ 496      ┆ PIT    ┆ BOS         │
│ 2001-06-30 23:59:00 ┆ 9     ┆ 151      ┆ ATL    ┆ HSV         │
│ 2001-06-30 23:59:00 ┆ 83    ┆ 641      ┆ DFW    ┆ DEN         │
│ 2001-06-30 23:59:00 ┆ 16    ┆ 594      ┆ ATL    ┆ DTW         │
└─────────────────────┴───────┴──────────┴────────┴─────────────┘
```

### CODE REVIEW

**Comment by domoritz** [comment]
It would be good to add the dependencies to the script so they can run with uvx.

**Comment by dangotbanned** [comment]
> It would be good to add the dependencies to the script so they can run with uvx.

@domoritz I've added what I assume would work, but the script is dependent on manually sourced data - so won't be able to run in ci.

I've been exploring rewriting the script in more reproducible way (locally), so I could follow this up with another PR?

**Comment by dsmedia** [comment]
Thanks for your help there. One issue is there does not appear to be an API
or programmatic way to retrieve the raw files.

**Comment by dangotbanned** [comment]
> Thanks for your help there. One issue is there does not appear to be an API or programmatic way to retrieve the raw files.
> […](#)

@dsmedia I've got that part solved 😅

**Comment by dsmedia** [comment]
Regarding the number of source months per dataset:

- all except flights-3m: three months (jan-mar) were chosen to match the timescale of the existing datasets. (The script was created to replicate the existing datasets.)

- flights-3m: six months of records were needed (jan-june) as this was the minimum timescale required to generate a dataset with 3 million records.

**Comment by domoritz** [comment]
Can we 

* get rid of https://github.com/vega/vega-datasets/blob/main/scripts/flights.js?
* put the commands to generate the parquet/csv etc files into the sources doc so that one can reproduce the files?

**Review by domoritz — APPROVED** [review]
Can we 

* get rid of https://github.com/vega/vega-datasets/blob/main/scripts/flights.js?
* put the commands to generate the parquet/csv etc files into the sources doc so that one can reproduce the files?

**Comment by dangotbanned** [comment]
Thanks for approving @domoritz 

> Can we
> 
> * put the commands to generate the parquet/csv etc files into the sources doc so that one can reproduce the files?

I'm going to follow this up with another PR in a next few days with a fully reproducible `flights.py`.

### Preview

<details><summary>Inputs declared in <code>toml</code></summary>
<p>

```toml
[[specs]]
range = [2001-01-01, 2001-03-31]
n_rows = 1_000
suffix = ".csv"
dt_format = "ISO"

[[specs]]
start = 2001-01-01
end = 2001-03-31
n_rows = 2_000
suffix = ".json"
dt_format = "iso"

[[specs]]
start = 2001-01-01
end = 2001-03-31
n_rows = 5_000
suffix = ".json"
dt_format = "iso"

[[specs]]
start = 2001-01-01
end = 2001-03-31
n_rows = 10_000
suffix = ".json"
dt_format = "iso"

[[specs]]
start = 2001-01-01
end = 2001-03-31
n_rows = 20_000
suffix = ".json"
dt_format = "iso"

[[specs]]
start = 2001-01-01
end = 2001-03-31
n_rows = 200_000
suffix = ".json"
dt_format = "decimal"
columns=["delay", "distance", "time"]

[[specs]]
start = 2001-01-01
end = 2001-03-31
n_rows = 200_000
suffix = ".arrow"
dt_format = "decimal"
columns=["delay", "distance", "time"]

[[specs]]
start = 2001-01-01
end = 2001-06-30
n_rows = 3_000_000
suffix = ".parquet"
```

</p>
</details> 

<details><summary>Downloading & sharing data</summary>
<p>


image

image


</p>
</details> 

<details><summary>Mix & match outputs</summary>
<p>

image

</p>
</details>

I just wanted to share this ahead of time to avoid repeating any work 😃

**Pull request merged**
